# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


jobs:

  - job: linux_builtin
    pool:
      vmImage: ubuntu-latest

    steps:
    - bash: |
        cd /home/vsts/work/_tasks/TfxInstaller_f7c56a03-d9d3-4019-b144-6283b88a66a8/5.0.538/
        ls -la
        cd /home/vsts/work/_tasks/TfxInstaller_f7c56a03-d9d3-4019-b144-6283b88a66a8/5.0.538/node_modules/.bin
        ls -la
    - task: TfxInstaller@5
      displayName: 'Use Node CLI for Azure DevOps (tfx-cli)'
      inputs:
        version: builtin